/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yujunkang_fangxinbao_utility_JniEncrypt */

#ifndef _Included_com_yujunkang_fangxinbao_utility_JniEncrypt
#define _Included_com_yujunkang_fangxinbao_utility_JniEncrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yujunkang_fangxinbao_utility_JniEncrypt
 * Method:    getEncryptString
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yujunkang_fangxinbao_utility_JniEncrypt_getEncryptString
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
